# Site settings
title: Bananagarden.net
baseurl: "" # /blog/
url: "http://bananagarden.net" # the base hostname & protocol for your site


# meta
copyright: bananagarden.net
author: bananagarden.net
keywords: 
description: i don`t know what i`m really doing 

# contacts
mail: depekur@gmail.com
twitter: https://twitter.com/depekur
github:  https://github.com/depekur


# Build settings
markdown: kramdown
excerpt_separator: <!--more-->