# Site settings
title: bananagarden.net
email: depekur@gmail.com

baseurl: "" # /blog/
url: "http://bananagarden.net" # the base hostname & protocol for your site


# meta
copyright: bananagarden.net
author: bananagarden.net
keywords: 
description: 

twitter_username: depekur
github_username:  depekur


# Build settings
markdown: kramdown
